annotation_tool/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'annotation_tool'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),

    url(r'^workspace/(?P<pk>\d+)/edit/$', views.Workspace, name='workspace'),
    path('blocks', views.BlockSelection, name='blocks'),
    path('uploadDOCX', views.UploadDOCX, name='uploadDOCX'),
    url(r'^save/(?P<pk>\d+)/(?P<model>\w+)/Entity/$',
        views.SaveEntity, name='saveEntity'),
    path('getLineDependencies', views.getLineDependencies,
         name='getLineDependencies'),

]

service_core/urls.py
from django.conf.urls import url
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^annotation_tool/', include('annotation_tool.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'annotation_tool.views.handler404'

annotation_tool/forms.py
from django.forms.widgets import ClearableFileInput
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from annotation_tool.models import UserProfileInfo, Relation, Object, Line, Block, Class, Description, Image


class UploadFileForm(forms.Form):
    file = forms.FileField()


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='Пароль')

    class Meta:
        model = User
        fields = ('username', 'password', 'email')
        labels = {
            'username': _('Логин'),
            'email': _('Почта'),
        }


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('name', 'surname')
        labels = {
            'name': _('Имя'),
            'surname': _('Фамилия'),
        }


class RelationForm(forms.ModelForm):
    class Meta:
        model = Relation
        fields = ('name',)
        labels = {
            'name': _('Название'),
        }


class ObjectForm(forms.ModelForm):
    class Meta:
        model = Object
        fields = ('name',)
        labels = {
            'name': _('Название'),
        }


class LineForm(forms.ModelForm):
    class Meta:
        model = Line
        fields = ('text_left', 'text_right',)
        labels = {
            'text_left': _('Оригинальный текст'),
            'text_right': _('Переведенный текст'),
        }


class BlockForm(forms.ModelForm):
    class Meta:
        model = Block
        fields = ('title',
                  'title_origin',
                  'language',
                  'dialect',
                  'theme',
                  'place_of_recording',
                  'time_of_recording',
                  'publisher',
                  'versions',
                  'area_of_distribution',

                  'initials',
                  'text_preparation',
                  'original_recording',
                  'text_decipher',
                  'translation',
                  'manager',
                  'commentary_preparation',)
        labels = {
            'title': _('Название'),
            'title_origin': _('Название на национальном языке'),
            'language': _('Язык'),
            'dialect': _('Диалект'),
            'theme': _('Жанр'),
            'place_of_recording': _('Место записи'),
            'time_of_recording': _('Время записи'),
            'publisher': _('Опубликовано (Выходные данные)'),
            'versions': _('Варианты'),
            'area_of_distribution': _('Ареал распространения'),

            'initials': _('ФИО'),
            'text_preparation': _('Подготовка текста'),
            'original_recording': _('Запись оригинала'),
            'text_decipher': _('Расшифровка текста'),
            'translation': _('Перевод на русский язык'),
            'manager': _('Редактор'),
            'commentary_preparation': _('Подготовка комментариев'),
        }


class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ('name', 'parent',)
        labels = {
            'parent': _('Родитель'),
            'name': _('Название'),
        }


class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        fields = ('text',)
        labels = {
            'text': _('Содержание'),
        }


class CustomImageFieldWidget(ClearableFileInput):
    template_with_clear = '<label for="%(clear_checkbox_id)s">%(clear)s %(clear_checkbox_label)s</label>'


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label=_('Обновить изображение'), required=False, error_messages={
        'invalid': _("Image files only")}, widget=forms.FileInput)

    class Meta:
        model = Image
        fields = ('name', 'image',)
        labels = {
            'name': _('Название'),
        }
        # widgets = {
        #     'image': CustomImageFieldWidget(),
        # }

annotation_tool/views.py
import openpyxl
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import authenticate, login, logout
import json
from django.db.models import Q
from django.apps import apps
from django.http import StreamingHttpResponse, HttpResponse, JsonResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

# main annotation_tool
from django.template import loader
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from docx import Document

from annotation_tool.forms import UploadFileForm, RelationForm, LineForm, BlockForm, ObjectForm, ClassForm, DescriptionForm, UserForm, UserProfileInfoForm, ImageForm
from annotation_tool.models import Block, Relation, Class, Line, Link, TaggedItem, Object, Description, UserProfileInfo, Image


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.is_active = False
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect('annotation_tool:user_login')
        else:
            mark = True
            return render(request, 'annotation_tool/authentication/registration.html',
                          {'user_form': user_form,
                           'profile_form': profile_form, 'mark': mark
                           })
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'annotation_tool/authentication/registration.html',
                  {'user_form': user_form,
                           'profile_form': profile_form,
                   })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('annotation_tool:blocks')
            else:
                return render(request, 'annotation_tool/authentication/loginError.html', {})
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return render(request, 'annotation_tool/authentication/loginError.html', {})
    else:
        return render(request, 'annotation_tool/authentication/login.html', {})


def handler404(request, exception):
    if request.user.is_authenticated:
        return redirect('annotation_tool:blocks')
    else:
        return redirect('annotation_tool:user_login')


def BlockSelection(request):
    if request.user.is_authenticated:
        blocks = Block.objects.all()
        return render(request, 'annotation_tool/blocks.html', {'blocks': blocks})
    else:
        return redirect('annotation_tool:user_login')


def UploadDOCX(request):
    if request.user.is_authenticated:
        if "GET" == request.method:
            form = UploadFileForm()
            return render(request, 'annotation_tool/uploadDOC.html', {'form': form})
        else:
            blocks = Block.objects.all()
            form = UploadFileForm(request.POST, request.FILES)
            # check whether it's valid:
            if form.is_valid():
                block = Block()
                file = form.cleaned_data['file']
                readDOCX(block, file)
                return render(request, 'annotation_tool/blocks.html', {'blocks': blocks})
    else:
        return redirect('annotation_tool:user_login')


def destroyAllLinks(element):
    tag = element.tags.first()
    Link.objects.filter(first_item=tag).delete()
    Link.objects.filter(second_item=tag).delete()


def SaveWindow(data):
    pk = data['pk']
    model = data['model']
    masters = json.loads(data['masters'])
    slaves = json.loads(data['slaves'])

    Model = apps.get_model(app_label="annotation_tool", model_name=model)
    current_item = Model.objects.get(pk=pk)
    destroyAllLinks(current_item)

    master_links = []
    if masters is not None:
        for k, elements in masters.items():
            if Relation.objects.filter(name=k).exists():
                relation = Relation.objects.get(name=k)
            else:
                relation = Relation(name=k)
                relation.save()
            for item in elements:
                Model = apps.get_model(
                    app_label="annotation_tool", model_name=item[0])
                object = Model.objects.get(pk=item[1])
                link = Link(relation=relation, first_item=object.tags.first(
                ), second_item=current_item.tags.first())
                link.save()

    slave_links = []
    if slaves is not None:
        for k, elements in slaves.items():
            if Relation.objects.filter(name=k).exists():
                relation = Relation.objects.get(name=k)
            else:
                relation = Relation(name=k)
                relation.save()
            for item in elements:
                Model = apps.get_model(
                    app_label="annotation_tool", model_name=item[0])
                object = Model.objects.get(pk=item[1])
                link = Link(relation=relation, first_item=current_item.tags.first(
                ), second_item=object.tags.first())
                link.save()


def Workspace(request, pk):
    if request.user.is_authenticated:
        block = Block.objects.get(pk=pk)
        lines = Line.objects.all().filter(block=block).order_by('position')
        return render(request, 'annotation_tool/main.html', {'lines': lines, 'pk': pk})
    else:
        return redirect('annotation_tool:user_login')

# else:
#     return HttpResponse('Not Authorized', status=403)


def SearchWindow():
    html = render_to_string('annotation_tool/windows/search.html',)
    return html


def Search(data):
    phrase = data['phrase']
    print(phrase)
    html = ''
    for block in Block.objects.all():
        html += showcase(block.pk, 'Block')
    for line in Line.objects.all():
        html += showcase(line.pk, 'Line')
    for obj in Object.objects.all():
        html += showcase(obj.pk, 'Object')
    for desc in Description.objects.all():
        html += showcase(desc.pk, 'Description')
    for img in Image.objects.all():
        html += showcase(img.pk, 'Image')
    return html


def ClassTree():
    html = render_to_string(
        'annotation_tool/windows/tree.html', {'genres': Class.objects.all()})
    return html


def PinFactory(data):
    model = data['model']
    Model = apps.get_model(
        app_label="annotation_tool", model_name=model)
    item = Model()
    item.save()
    item_html = showcase(item.pk, model)
    return item_html


def PinFactoryWindow():
    html = render_to_string('annotation_tool/windows/pinFactory.html')
    return html


@csrf_exempt
def SaveEntity(request, pk, model):
    if request.user.is_authenticated:
        Model = apps.get_model(
            app_label="annotation_tool", model_name=model)
        item = get_object_or_404(Model, pk=pk)
        if request.method == "POST":
            GenericForm = getForm(model)
            form = GenericForm(request.POST, instance=item,
                               files=request.FILES)
            if form.is_valid():
                item = form.save(commit=False)
                item.save()
                return HttpResponse("Сохранено")
            else:
                return HttpResponse("Ошибка в форме")
    else:
        return redirect('annotation_tool:user_login')


def InfoWindow(pk, model_name):
    Model = apps.get_model(
        app_label="annotation_tool", model_name=model_name)
    if Model.objects.filter(pk=pk).exists():
        obj = Model.objects.get(pk=pk)
        slaves, masters = getAllLinks(obj)

        GenericForm = getForm(model_name)
        form = GenericForm(instance=obj)

        item_html = showcase(pk, model_name, False)
        slaves_html = ""
        masters_html = ""

        for key, item in slaves.items():
            slaves_html += '<div class="item-dep"> <p>' + key + ':</p>'
            slaves_html += '<div class ="placeholder"  data-dep-name="' + \
                key+'" data-dep-role="slaves">'
            for i in item:
                slaves_html += showcase(i.pk, i.__class__.__name__)
            slaves_html += '</div></div>'

        for key, item in masters.items():
            masters_html += '<div class="item-dep"> <p>' + key + ':</p>'
            masters_html += '<div class ="placeholder" data-dep-name="' + \
                key+'" data-dep-role="masters">'
            for i in item:
                masters_html += showcase(i.pk, i.__class__.__name__)
            masters_html += '</div></div>'

        html = render_to_string('annotation_tool/windows/info.html',
                                {'item': item_html, 'masters': masters_html, 'slaves': slaves_html, 'obj': obj, 'form': form})
        return html


def showcase(pk, model_name, pin=True):
    Model = apps.get_model(app_label="annotation_tool", model_name=model_name)
    if Model.objects.filter(pk=pk).exists():
        name = model_name.lower()
        item = Model.objects.get(pk=pk)
        html = render_to_string(
            'annotation_tool/showcase/' + name + '.html', {'item': item, 'pin': pin})
        return html


@csrf_exempt
def getLineDependencies(request):
    if request.user.is_authenticated:
        if request.is_ajax():
            block_pk = request.GET.get('pk')
            if Block.objects.filter(pk=block_pk).exists():

templates/annotation_tool/blocks.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Антология</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fixer-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/article-style.css' %}">
    <script src="{% static 'js/preload.js' %}"></script>
</head>
<a href="{% url 'annotation_tool:uploadDOCX'%}" class="uploadlink">
    <p>&#9870;</p>
</a>

<body>
    {% comment %} <div class="se-pre-con"></div> {% endcomment %}
    <div class="content">
        <div class="block">
            <p>Выберите блок для маркировки:</p>
        </div>
        {% if blocks %}
        {% for block in blocks %}
        <div class="article">
            <a href="{% url 'annotation_tool:workspace' pk=block.pk %}">{{ block.title }}</a>
        </div>
        {% endfor %}
        {% else %}
        <div class="article">
            <a href="">Нет блоков</a>
        </div>
        {% endif %}
    </div>
</body>

</html>

templates/annotation_tool/create.html
{% extends "annotation_tool/window.html" %}
{% load tags %}

{% block content %}
<div class="create-container">
    <div class="select-container">
        <select class="model-select">
            <option value="Object">Объект</option>
            <option value="Class">Класс</option>
            <option value="Description">Описание</option>
            <option value="Image">Изображение</option>
            <option value="Audio">Аудио</option>
            <option value="Video">Видео</option>
        </select>
        <div id="confirm-select"><p><i class="fas fa-search"></i></p></div>
        <div id="save-object"><p><i class="fas fa-save"></i></p></div>
    </div>
    <div class="input-container">
    </div>
</div>
{% endblock content %}

templates/annotation_tool/forms.html
{% comment %} {% if any %}
{{ form }}
{% else %}

{% endif %} {% endcomment %}

templates/annotation_tool/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load tags %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Интерфейс</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fixer-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tooltip-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/window-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/search-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tree-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/create-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/item-style.css' %}">


    <script src= "{% static 'js/tooltip.js' %}"></script>
    <script src= "{% static 'js/preload.js' %}"></script>
    <script src= "{% static 'js/SelectionTool.js' %}"></script>
    <script src= "{% static 'js/classes/Window.js' %}"></script>
    <script src= "{% static 'js/controllers/WindowController.js' %}"></script>
    <script src= "{% static 'js/controllers/WindowWorkflow.js' %}"></script>
    <script src= "{% static 'js/handlers.js' %}"></script>
</head>
<body>
{% comment %} <div class="se-pre-con"></div> {% endcomment %}
<div id="window-container"></div>
<div id="hidden-window-container"></div>
<div id="side-item-info"></div>

<a href="{% url 'annotation_tool:blocks'%}" class="articlelink"><p><i class="fas fa-list-alt"></i></p></a>
<div id="hide-all-windows"><p><i class="fas fa-eye-slash"></i></p></div>
<div id="close-all-windows"><p><i class="fas fa-times"></i></p></div>
<div id="open-search"><p><i class="fas fa-search"></i></p></div>
<div id="open-tree"><p><i class="fas fa-project-diagram"></i></p></div>
<div id="pin-factory"><p><i class="fas fa-plus"></i></p></div>
<iframe name="dump" width="0" height="0"></iframe>    
    <div class="block" id="block" data-pk="{{ pk }}">
        {% if lines %}
            {% for line in lines %}
                    {% comment %} <div style="grid-column: 1; grid-row: {{line.position}}" class="id" id="{{ line.pk }}" data-callable="1" data-pk="{{ line.pk }}" data-model="{{ line|get_class}}">
                        <p>{{line.position}}</p>
                        <div class="item-open" data-callable="1"><p>open</p></div>
                    </div> {% endcomment %}
                    <div class="item" data-pk="{{line.pk}}" data-model="{{ line|get_class }}">
                        <p style="display: none">Строка - </p><p style="min-width: 20px">{{ line.position }}</p>
                        <div class="item-delete" style="display: none"><p><i class="fas fa-times"></i></p></div>
                        <div class="item-open"><p><i class="far fa-sticky-note"></i></p></div>
                        <div class="item-info">
                            <div class="content">
                                <div class="label"><p>Оригинал:</p></div>
                                <div class="value"><p data-callable="1" data-pk="{{line.pk}}" data-model="{{ line|get_class }}">Оригинал</p></div>
                                <div class="label"><p>Содержится в блоке::</p></div>
                                <div class="value"><p data-callable="1" data-pk="{{line.block.pk}}" data-model="{{ line.block|get_class }}">{{ line.block.title }}</p></div>
                                <div class="label"><p>Позиция:</p></div>
                                <div class="value"><p>{{ line.position }}</p></div>
                                <div class="label"><p>Оригинальный текст:</p></div>
                                <div class="value"><p>{{ line.text_left }}</p></div>
                                <div class="label"><p>Переведенный текст:</p></div>
                                <div class="value"><p>{{ line.text_right }}</p></div>
                            </div>
                        </div>
                    </div>
                    <div style="" class="line"><p>{{ line.text_left }}</p></div>
                    <div style="" class="line" ><p>{{ line.text_right }}</p></div>
            {% endfor %}
        {% endif %}
    </div>

</body>
</html>

templates/annotation_tool/uploadDOC.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load widget_tweaks %}
    {% load static %}
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fixer-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/upload-style.css' %}">
    
    <script src= "{% static 'js/uploadFile.js' %}"></script>
</head>
<body>

    <div class="content">
        <form enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            {% render_field form.file %}
            <button type="submit"><p><i class="fas fa-file-upload"></i></p></button>
        </form>
    </div>
    <div class="box">
			<div class="loader3"></div>
			<p>loader 3</p>
	</div>

    
<div id="wrapper">
   	  <div id="slider-wrap">
      	  <ul id="slider">
          	 <li data-color="#1abc9c" style="background: url('{% static 'images/test.png' %}')">
                <div>
                    <h3>Slide #1</h3>
                    <span>Sub-title #1</span>
                </div>                
             </li>
             
             <li data-color="#3498db">
                <div>
                    <h3>Slide #2</h3>
                    <span>Sub-title #2</span>
                </div>
                <i class="fa fa-gears"></i>
             </li> 
          </ul>
           <!--controls-->
          <div class="btns" id="next"><i class="fa fa-arrow-right"></i></div>
          <div class="btns" id="previous"><i class="fa fa-arrow-left"></i></div>
          <div id="counter"></div>
          
          <div id="pagination-wrap">
            <ul>
            </ul>
          </div>
          <!--controls-->  
                 
      </div>
  
   </div>


</body>
</html>

templates/annotation_tool/uploadXLS.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load widget_tweaks %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/fixer-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/article-style.css' %}">

</head>
<body>

{#<form action="{% url "annotation_tool:uploadXML" %}" method="post" enctype="multipart/form-data">#}
{#            {% csrf_token %}#}
{#            <input type="file"#}
{#                   title="Upload excel file"#}
{#                   name="excel_file"#}
{#                   style="border: 1px solid black; padding: 5px;"#}
{#                   required="required">#}
{#            <p>#}
{#            <input type="submit"#}
{#                   value="Upload"#}
{#                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">#}
{#</form>#}


<div class="content">
    <form enctype="multipart/form-data" action="" method="post"> <!-- Do not forget to add: enctype="multipart/form-data" -->
            {% csrf_token %}
        <div class="block-file">
            <label>
                {% render_field form.file %}
                <span>Выберите Excel документ</span>
            </label>
        </div>


    <input type="submit" value="Загрузить текст">
</form>
</div>
</body>
</html>