annotation_tool/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'annotation_tool'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),

    url(r'^workspace/(?P<pk>\d+)/edit/$', views.Workspace, name='workspace'),
    path('blocks', views.BlockSelection, name='blocks'),
    path('uploadDOCX', views.UploadDOCX, name='uploadDOCX'),
    url(r'^save/(?P<pk>\d+)/(?P<model>\w+)/Entity/$',
        views.SaveEntity, name='saveEntity'),
    path('getLineDependencies', views.getLineDependencies,
         name='getLineDependencies'),

]

service_core/urls.py
from django.conf.urls import url
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^annotation_tool/', include('annotation_tool.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'annotation_tool.views.handler404'

annotation_tool/forms.py
from django.forms.widgets import ClearableFileInput
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from annotation_tool.models import UserProfileInfo, Relation, Object, Line, Block, Class, Description, Image


class UploadFileForm(forms.Form):
    file = forms.FileField()


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='Пароль')

    class Meta:
        model = User
        fields = ('username', 'password', 'email')
        labels = {
            'username': _('Логин'),
            'email': _('Почта'),
        }


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('name', 'surname')
        labels = {
            'name': _('Имя'),
            'surname': _('Фамилия'),
        }


class RelationForm(forms.ModelForm):
    class Meta:
        model = Relation
        fields = ('name',)
        labels = {
            'name': _('Название'),
        }


class ObjectForm(forms.ModelForm):
    class Meta:
        model = Object
        fields = ('name',)
        labels = {
            'name': _('Название'),
        }


class LineForm(forms.ModelForm):
    class Meta:
        model = Line
        fields = ('text_left', 'text_right',)
        labels = {
            'text_left': _('Оригинальный текст'),
            'text_right': _('Переведенный текст'),
        }


class BlockForm(forms.ModelForm):
    class Meta:
        model = Block
        fields = ('title',
                  'title_origin',
                  'language',
                  'dialect',
                  'theme',
                  'place_of_recording',
                  'time_of_recording',
                  'publisher',
                  'versions',
                  'area_of_distribution',

                  'initials',
                  'text_preparation',
                  'original_recording',
                  'text_decipher',
                  'translation',
                  'manager',
                  'commentary_preparation',)
        labels = {
            'title': _('Название'),
            'title_origin': _('Название на национальном языке'),
            'language': _('Язык'),
            'dialect': _('Диалект'),
            'theme': _('Жанр'),
            'place_of_recording': _('Место записи'),
            'time_of_recording': _('Время записи'),
            'publisher': _('Опубликовано (Выходные данные)'),
            'versions': _('Варианты'),
            'area_of_distribution': _('Ареал распространения'),

            'initials': _('ФИО'),
            'text_preparation': _('Подготовка текста'),
            'original_recording': _('Запись оригинала'),
            'text_decipher': _('Расшифровка текста'),
            'translation': _('Перевод на русский язык'),
            'manager': _('Редактор'),
            'commentary_preparation': _('Подготовка комментариев'),
        }


class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ('name', 'parent',)
        labels = {
            'parent': _('Родитель'),
            'name': _('Название'),
        }


class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        fields = ('text',)
        labels = {
            'text': _('Содержание'),
        }


class CustomImageFieldWidget(ClearableFileInput):
    template_with_clear = '<label for="%(clear_checkbox_id)s">%(clear)s %(clear_checkbox_label)s</label>'


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label=_('Обновить изображение'), required=False, error_messages={
        'invalid': _("Image files only")}, widget=forms.FileInput)

    class Meta:
        model = Image
        fields = ('name', 'image',)
        labels = {
            'name': _('Название'),
        }
        # widgets = {
        #     'image': CustomImageFieldWidget(),
        # }

annotation_tool/views.py
import openpyxl
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import authenticate, login, logout
import json
from django.db.models import Q
from django.apps import apps
from django.http import StreamingHttpResponse, HttpResponse, JsonResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

# main annotation_tool
from django.template import loader
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from docx import Document

from annotation_tool.forms import UploadFileForm, RelationForm, LineForm, BlockForm, ObjectForm, ClassForm, DescriptionForm, UserForm, UserProfileInfoForm, ImageForm
from annotation_tool.models import Block, Relation, Class, Line, Link, TaggedItem, Object, Description, UserProfileInfo, Image


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.is_active = False
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect('annotation_tool:user_login')
        else:
            mark = True
            return render(request, 'annotation_tool/authentication/registration.html',
                          {'user_form': user_form,
                           'profile_form': profile_form, 'mark': mark
                           })
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'annotation_tool/authentication/registration.html',
                  {'user_form': user_form,
                           'profile_form': profile_form,
                   })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('annotation_tool:blocks')
            else:
                return render(request, 'annotation_tool/authentication/loginError.html', {})
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return render(request, 'annotation_tool/authentication/loginError.html', {})
    else:
        return render(request, 'annotation_tool/authentication/login.html', {})


def handler404(request, exception):
    if request.user.is_authenticated:
        return redirect('annotation_tool:blocks')
    else:
        return redirect('annotation_tool:user_login')


def BlockSelection(request):
    if request.user.is_authenticated:
        blocks = Block.objects.all()
        return render(request, 'annotation_tool/blocks.html', {'blocks': blocks})
    else:
        return redirect('annotation_tool:user_login')


def UploadDOCX(request):
    if request.user.is_authenticated:
        if "GET" == request.method:
            form = UploadFileForm()
            return render(request, 'annotation_tool/uploadDOC.html', {'form': form})
        else:
            blocks = Block.objects.all()
            form = UploadFileForm(request.POST, request.FILES)
            # check whether it's valid:
            if form.is_valid():
                block = Block()
                file = form.cleaned_data['file']
                readDOCX(block, file)
                return render(request, 'annotation_tool/blocks.html', {'blocks': blocks})
    else:
        return redirect('annotation_tool:user_login')


def destroyAllLinks(element):
    tag = element.tags.first()
    Link.objects.filter(first_item=tag).delete()
    Link.objects.filter(second_item=tag).delete()


def SaveWindow(data):
    pk = data['pk']
    model = data['model']
    masters = json.loads(data['masters'])
    slaves = json.loads(data['slaves'])

    Model = apps.get_model(app_label="annotation_tool", model_name=model)
    current_item = Model.objects.get(pk=pk)
    destroyAllLinks(current_item)

    master_links = []
    if masters is not None:
        for k, elements in masters.items():
            if Relation.objects.filter(name=k).exists():
                relation = Relation.objects.get(name=k)
            else:
                relation = Relation(name=k)
                relation.save()
            for item in elements:
                Model = apps.get_model(
                    app_label="annotation_tool", model_name=item[0])
                object = Model.objects.get(pk=item[1])
                link = Link(relation=relation, first_item=object.tags.first(
                ), second_item=current_item.tags.first())
                link.save()

    slave_links = []
    if slaves is not None:
        for k, elements in slaves.items():
            if Relation.objects.filter(name=k).exists():
                relation = Relation.objects.get(name=k)
            else:
                relation = Relation(name=k)
                relation.save()
            for item in elements:
                Model = apps.get_model(
                    app_label="annotation_tool", model_name=item[0])
                object = Model.objects.get(pk=item[1])
                link = Link(relation=relation, first_item=current_item.tags.first(
                ), second_item=object.tags.first())
                link.save()


def Workspace(request, pk):
    if request.user.is_authenticated:
        block = Block.objects.get(pk=pk)
        lines = Line.objects.all().filter(block=block).order_by('position')
        return render(request, 'annotation_tool/main.html', {'lines': lines, 'pk': pk})
    else:
        return redirect('annotation_tool:user_login')

# else:
#     return HttpResponse('Not Authorized', status=403)


def SearchWindow():
    html = render_to_string('annotation_tool/windows/search.html',)
    return html


def Search(data):
    phrase = data['phrase']
    print(phrase)
    html = ''
    for block in Block.objects.all():
        html += showcase(block.pk, 'Block')
    for line in Line.objects.all():
        html += showcase(line.pk, 'Line')
    for obj in Object.objects.all():
        html += showcase(obj.pk, 'Object')
    for desc in Description.objects.all():
        html += showcase(desc.pk, 'Description')
    for img in Image.objects.all():
        html += showcase(img.pk, 'Image')
    return html


def ClassTree():
    html = render_to_string(
        'annotation_tool/windows/tree.html', {'genres': Class.objects.all()})
    return html


def PinFactory(data):
    model = data['model']
    Model = apps.get_model(
        app_label="annotation_tool", model_name=model)
    item = Model()
    item.save()
    item_html = showcase(item.pk, model)
    return item_html


def PinFactoryWindow():
    html = render_to_string('annotation_tool/windows/pinFactory.html')
    return html


@csrf_exempt
def SaveEntity(request, pk, model):
    if request.user.is_authenticated:
        Model = apps.get_model(
            app_label="annotation_tool", model_name=model)
        item = get_object_or_404(Model, pk=pk)
        if request.method == "POST":
            GenericForm = getForm(model)
            form = GenericForm(request.POST, instance=item,
                               files=request.FILES)
            if form.is_valid():
                item = form.save(commit=False)
                item.save()
                return HttpResponse("Сохранено")
            else:
                return HttpResponse("Ошибка в форме")
    else:
        return redirect('annotation_tool:user_login')


def InfoWindow(pk, model_name):
    Model = apps.get_model(
        app_label="annotation_tool", model_name=model_name)
    if Model.objects.filter(pk=pk).exists():
        obj = Model.objects.get(pk=pk)
        slaves, masters = getAllLinks(obj)

        GenericForm = getForm(model_name)
        form = GenericForm(instance=obj)

        item_html = showcase(pk, model_name, False)
        slaves_html = ""
        masters_html = ""

        for key, item in slaves.items():
            slaves_html += '<div class="item-dep"> <p>' + key + ':</p>'
            slaves_html += '<div class ="placeholder"  data-dep-name="' + \
                key+'" data-dep-role="slaves">'
            for i in item:
                slaves_html += showcase(i.pk, i.__class__.__name__)
            slaves_html += '</div></div>'

        for key, item in masters.items():
            masters_html += '<div class="item-dep"> <p>' + key + ':</p>'
            masters_html += '<div class ="placeholder" data-dep-name="' + \
                key+'" data-dep-role="masters">'
            for i in item:
                masters_html += showcase(i.pk, i.__class__.__name__)
            masters_html += '</div></div>'

        html = render_to_string('annotation_tool/windows/info.html',
                                {'item': item_html, 'masters': masters_html, 'slaves': slaves_html, 'obj': obj, 'form': form})
        return html


def showcase(pk, model_name, pin=True):
    Model = apps.get_model(app_label="annotation_tool", model_name=model_name)
    if Model.objects.filter(pk=pk).exists():
        name = model_name.lower()
        item = Model.objects.get(pk=pk)
        html = render_to_string(
            'annotation_tool/showcase/' + name + '.html', {'item': item, 'pin': pin})
        return html


@csrf_exempt
def getLineDependencies(request):
    if request.user.is_authenticated:
        if request.is_ajax():
            block_pk = request.GET.get('pk')
            if Block.objects.filter(pk=block_pk).exists():

templates/annotation_tool/authentication/authError.html
{% extends "annotation_tool/authentication/base.html" %}
{% block title %}
Ошибка аутентификации
{% endblock title %}

        <div class="title-error"><p>Ошибка входа</p></div>
        <p class="headline-error">Причина:</p>
        <div class="causes" style="height: 52px;">
            <p>Данный ресурс предназначен для администратора сети</p>
        </div>
        <div class="return"><a href="{% url 'annotation_tool:blocks' %}">Вернуться на главную страницу</a> </div>
{% block content %}
{% endblock content %}

templates/annotation_tool/authentication/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load tags %}
    {% load widget_tweaks %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fixer-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth-style.css' %}">

    <script src= "{% static 'js/preload.js' %}"></script>
</head>
<body>
    <div class="se-pre-con"></div>
    <div class="container">
    {% block content %}
    {% endblock content %}
    </div>
</body>
</html>

templates/annotation_tool/authentication/login.html
{% extends "annotation_tool/authentication/base.html" %}
{% block title %}
Вход
{% endblock title %}
{% block content %}
        <div class="title">
            <p>Авторизация</p>
        </div>
        <form method="post" action="{% url 'annotation_tool:user_login' %}">
                    {% csrf_token %}
                    {# A more "HTML" way of creating the login form#}
                    <div class="label-holder"><label for="username">Логин:</label></div>
                    <input type="text" name="username" placeholder="Введите логин">
                    <div class="label-holder"><label for="password">Пароль:</label></div>
                    <input type="password" name="password" placeholder="Введите пароль">
                    <button type="submit" name="" value="Login"><p>Войти в систему</p></button>
                    <button style="background-color: rgb(255,70,65)"><a href="{% url 'annotation_tool:register'%}">Регистрация</a></button>
        </form>
{% endblock content %}

templates/annotation_tool/authentication/loginError.html
{% extends "annotation_tool/authentication/base.html" %}
{% block title %}
Ошибка входа
{% endblock title %}


{% block content %}
        <div class="title-error"><p>Ошибка входа</p></div>
        <p class="headline-error">Возможные причины:</p>
        <div class="causes">
            <p>&bull; Ошибка при вводе логина и пароля</p>
            <p>&bull; Ваша учетная запись была деактивирована</p>
            <p>&bull; Если вы новый пользователь сети, то обратитесь к администратору для активации вашей учетной записи</p>
        </div>
        <div class="return"><a href="{% url 'annotation_tool:user_login' %}">Вернуться на страницу входа</a> </div>
{% endblock content %}

templates/annotation_tool/authentication/registration.html
{% extends "annotation_tool/authentication/base.html" %}
{% load widget_tweaks %}
{% block title %}
Регистрация
{% endblock title %}


{% block content %}
        <div class="title"><p>Регистрация</p></div>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <div class="label-holder">
                    <label>{{ user_form.username.label }}:</label>
                </div>
                {% render_field user_form.username %}

                <div class="label-holder">
                    <label>{{ user_form.password.label }}:</label>
                </div>
                {% render_field user_form.password %}

                <div class="label-holder">
                    <label>{{ user_form.email.label }}:</label>
                </div>
                {% render_field user_form.email %}

                 <div class="label-holder">
                     <label>{{ profile_form.name.label }}:</label>
                 </div>
                {% render_field profile_form.name %}

                 <div class="label-holder">
                     <label>{{ profile_form.surname.label }}:</label>
                 </div>
                {% render_field profile_form.surname %}

                <button style="background-color: rgb(255,70,65)" type="submit" name="" value="Register"><p>Создать учетную запись</p></button>
            </form>
         {% if mark %}
             <div class="username-error"><p>Пользователь с данным логином уже существует</p></div>
        {% endif %}
{% endblock content %}